//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSPKBordir
    {
        public int idSPKBordir { get; set; }
        public string noSPKBordir { get; set; }
        public int EmployeeiD { get; set; }
        public System.DateTime Datetime { get; set; }
        public int status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
