//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPenjualanBaju
    {
        public int idDPB { get; set; }
        public string noPenjualan { get; set; }
        public int CustomerID { get; set; }
        public decimal GrandTotal { get; set; }
        public System.DateTime Datetime { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
