//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPemotonganKain
    {
        public int idPemotonganKain { get; set; }
        public string noPemotonganKain { get; set; }
        public string NoFaktur { get; set; }
        public long PONumber { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date_time { get; set; }
        public int status { get; set; }
    
        public virtual DetailFaktur DetailFaktur { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PreOrderKain PreOrderKain { get; set; }
    }
}
