//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSPK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailSPK()
        {
            this.PenerimaanSBCs = new HashSet<PenerimaanSBC>();
        }
    
        public int idSPK { get; set; }
        public string noSPK { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string type { get; set; }
        public int status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenerimaanSBC> PenerimaanSBCs { get; set; }
    }
}
