//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPenerimaanSBC
    {
        public int idDetail { get; set; }
        public string noPenerimaan { get; set; }
        public string noSPK { get; set; }
        public string noSeri { get; set; }
        public string type { get; set; }
        public int tempSablon { get; set; }
        public int tempBordir { get; set; }
        public int tempCMT { get; set; }
    }
}
