//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenerimaanSBC
    {
        public int id { get; set; }
        public string noPenerimaan { get; set; }
        public string noSPK { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int status { get; set; }
    }
}
