//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityRecord
    {
        public int id { get; set; }
        public string noSeri { get; set; }
        public Nullable<double> qtyAwalSablon { get; set; }
        public Nullable<double> qtySablonBS { get; set; }
        public Nullable<double> qtySablonHilang { get; set; }
        public Nullable<double> qtyAwalBordir { get; set; }
        public Nullable<double> qtyBordirBS { get; set; }
        public Nullable<double> qtyBordirHilang { get; set; }
        public Nullable<double> qtyAwalCMT { get; set; }
        public Nullable<double> qtyCMTBS { get; set; }
        public Nullable<double> qtyCMTHilang { get; set; }
    }
}
